///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace KeepassUnik
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClickMenu recording.
    /// </summary>
    [TestModule("ae27727a-7e16-4b1a-a779-73cee8687652", ModuleType.Recording, 1)]
    public partial class ClickMenu : ITestModule
    {
        /// <summary>
        /// Holds an instance of the KeepassUnikRepository repository.
        /// </summary>
        public static KeepassUnikRepository repo = KeepassUnikRepository.Instance;

        static ClickMenu instance = new ClickMenu();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClickMenu()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClickMenu Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varMenuNavn.
        /// </summary>
        [TestVariable("ef6ddf8a-43e2-431e-a3c7-2c8ca827bc12")]
        public string varMenuNavn
        {
            get { return repo.varMenuNavn; }
            set { repo.varMenuNavn = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainForm.MTvGroups.MenuNavn' at 25;5.", repo.MainForm.MTvGroups.MenuNavnInfo, new RecordItemIndex(0));
            repo.MainForm.MTvGroups.MenuNavn.Click("25;5");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
