///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace KeepassUnik
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the KeepassUnikRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("9dd8e404-4a8f-49e4-ab79-02b042a3b3ad")]
    public partial class KeepassUnikRepository : RepoGenBaseFolder
    {
        static KeepassUnikRepository instance = new KeepassUnikRepository();
        KeepassUnikRepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        KeepassUnikRepositoryFolders.MainFormXAppFolder _mainformx;

        /// <summary>
        /// Gets the singleton class instance representing the KeepassUnikRepository element repository.
        /// </summary>
        [RepositoryFolder("9dd8e404-4a8f-49e4-ab79-02b042a3b3ad")]
        public static KeepassUnikRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public KeepassUnikRepository() 
            : base("KeepassUnikRepository", "/", null, 0, false, "9dd8e404-4a8f-49e4-ab79-02b042a3b3ad", ".\\RepositoryImages\\KeepassUnikRepository9dd8e404.rximgres")
        {
            _keypromptform = new KeepassUnikRepositoryFolders.KeyPromptFormAppFolder(this);
            _mainformx = new KeepassUnikRepositoryFolders.MainFormXAppFolder(this);
        }

#region Variables

        string _varMenuNavn = "General";

        /// <summary>
        /// Gets or sets the value of variable varMenuNavn.
        /// </summary>
        [TestVariable("ef6ddf8a-43e2-431e-a3c7-2c8ca827bc12")]
        public string varMenuNavn
        {
            get { return _varMenuNavn; }
            set { _varMenuNavn = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("9dd8e404-4a8f-49e4-ab79-02b042a3b3ad")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("884d3a65-4af8-46b0-b3c0-9c59bdd98224")]
        public virtual KeepassUnikRepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The MainFormX folder.
        /// </summary>
        [RepositoryFolder("d844fd5c-6366-4513-ad30-50f4a59f9547")]
        public virtual KeepassUnikRepositoryFolders.MainFormXAppFolder MainFormX
        {
            get { return _mainformx; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class KeepassUnikRepositoryFolders
    {
        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("884d3a65-4af8-46b0-b3c0-9c59bdd98224")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mbtnokInfo;
            RepoItemInfo _textInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@controlname='KeyPromptForm']", parentFolder, 30, null, true, "884d3a65-4af8-46b0-b3c0-9c59bdd98224", "")
            {
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@controlname='m_btnOK']", 30000, null, "7de19fe0-ac3f-4e98-aba8-1ba57f1c16cd");
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", 30000, null, "8fc224a4-e750-431b-a81f-426a011f46bb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("884d3a65-4af8-46b0-b3c0-9c59bdd98224")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("884d3a65-4af8-46b0-b3c0-9c59bdd98224")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("7de19fe0-ac3f-4e98-aba8-1ba57f1c16cd")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("7de19fe0-ac3f-4e98-aba8-1ba57f1c16cd")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("8fc224a4-e750-431b-a81f-426a011f46bb")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("8fc224a4-e750-431b-a81f-426a011f46bb")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormXAppFolder folder.
        /// </summary>
        [RepositoryFolder("d844fd5c-6366-4513-ad30-50f4a59f9547")]
        public partial class MainFormXAppFolder : RepoGenBaseFolder
        {
            KeepassUnikRepositoryFolders.MTvGroupsFolder _mtvgroups;
            RepoItemInfo _newdatabasekdbxkeepasspasswordsafeInfo;

            /// <summary>
            /// Creates a new MainFormX  folder.
            /// </summary>
            public MainFormXAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainFormX", "/form[@controlname='MainForm']", parentFolder, 30000, null, true, "d844fd5c-6366-4513-ad30-50f4a59f9547", "")
            {
                _mtvgroups = new KeepassUnikRepositoryFolders.MTvGroupsFolder(this);
                _newdatabasekdbxkeepasspasswordsafeInfo = new RepoItemInfo(this, "NewDatabaseKdbxKeePassPasswordSafe", "titlebar[@accessiblerole='TitleBar']", 30000, null, "4e998767-ecd1-4162-8db6-ed15b24ae472");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d844fd5c-6366-4513-ad30-50f4a59f9547")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d844fd5c-6366-4513-ad30-50f4a59f9547")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewDatabaseKdbxKeePassPasswordSafe item.
            /// </summary>
            [RepositoryItem("4e998767-ecd1-4162-8db6-ed15b24ae472")]
            public virtual Ranorex.TitleBar NewDatabaseKdbxKeePassPasswordSafe
            {
                get
                {
                    return _newdatabasekdbxkeepasspasswordsafeInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The NewDatabaseKdbxKeePassPasswordSafe item info.
            /// </summary>
            [RepositoryItemInfo("4e998767-ecd1-4162-8db6-ed15b24ae472")]
            public virtual RepoItemInfo NewDatabaseKdbxKeePassPasswordSafeInfo
            {
                get
                {
                    return _newdatabasekdbxkeepasspasswordsafeInfo;
                }
            }

            /// <summary>
            /// The MTvGroups folder.
            /// </summary>
            [RepositoryFolder("baced42b-1106-470a-96f8-dc1f09bab15b")]
            public virtual KeepassUnikRepositoryFolders.MTvGroupsFolder MTvGroups
            {
                get { return _mtvgroups; }
            }
        }

        /// <summary>
        /// The MTvGroupsFolder folder.
        /// </summary>
        [RepositoryFolder("baced42b-1106-470a-96f8-dc1f09bab15b")]
        public partial class MTvGroupsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menunavnInfo;

            /// <summary>
            /// Creates a new MTvGroups  folder.
            /// </summary>
            public MTvGroupsFolder(RepoGenBaseFolder parentFolder) :
                    base("MTvGroups", "container[@controlname='m_splitHorizontal']//tree[@controlname='m_tvGroups']", parentFolder, 30000, null, false, "baced42b-1106-470a-96f8-dc1f09bab15b", "")
            {
                _menunavnInfo = new RepoItemInfo(this, "MenuNavn", "?/?/treeitem[@accessiblename='NewDatabase']/treeitem[@accessiblename=$varMenuNavn]", 30000, null, "9da1cc1d-118f-4f30-9fa8-7f0476e96f13");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("baced42b-1106-470a-96f8-dc1f09bab15b")]
            public virtual Ranorex.Tree Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("baced42b-1106-470a-96f8-dc1f09bab15b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuNavn item.
            /// </summary>
            [RepositoryItem("9da1cc1d-118f-4f30-9fa8-7f0476e96f13")]
            public virtual Ranorex.TreeItem MenuNavn
            {
                get
                {
                    return _menunavnInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The MenuNavn item info.
            /// </summary>
            [RepositoryItemInfo("9da1cc1d-118f-4f30-9fa8-7f0476e96f13")]
            public virtual RepoItemInfo MenuNavnInfo
            {
                get
                {
                    return _menunavnInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}